# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4NM7-yVQrpSdIiVuQr9aHqT_-MbxnOT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Sabse pehle apna data load karo (apni file ka sahi naam/path yahan likho)
# Agar aapki file ka naam 'cleaned_ecommerce.csv' hai toh:
df = pd.read_csv('cleaned_ecommerce.csv')

# 2. InvoiceDate column ko datetime format mein convert karna zaroori hai
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# 3. Ab month extract karo aur group karo
df['Month'] = df['InvoiceDate'].dt.strftime('%B')
months_order = ['January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December']

monthly_sales = df.groupby('Month')['TotalAmount'].sum().reindex(months_order).reset_index()

# 4. Plotting Line Chart
plt.figure(figsize=(10, 5))
sns.lineplot(data=monthly_sales, x='Month', y='TotalAmount', marker='o', color='#0A2540', linewidth=2.5)

plt.title('Sum of TotalAmount by Month', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Month', fontsize=12)
plt.ylabel('Sum of TotalAmount', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

# Save image for GitHub
plt.savefig('monthly_sales_trend.png', dpi=300)
plt.show()

# 1. Top 5 ya 10 products group karna
top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(6).reset_index()

# 2. Plotting
plt.figure(figsize=(10, 5))
sns.barplot(data=top_products, x='Quantity', y='Description', color='#002060')

plt.title('Sum of Quantity by Description', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Sum of Quantity', fontsize=12)
plt.ylabel('Description', fontsize=12)
plt.tight_layout()

# Save image for GitHub
plt.savefig('top_products_quantity.png', dpi=300)
plt.show()

import plotly.express as px

# 1. Country wise sales aggregation
country_sales = df.groupby('Country')['TotalAmount'].sum().reset_index()

# 2. Interactive Treemap using Plotly
fig = px.treemap(country_sales,
                 path=['Country'],
                 values='TotalAmount',
                 title='Sum of TotalAmount by Country',
                 color='TotalAmount',
                 color_continuous_scale='Blues')

fig.update_layout(title_font=dict(size=18, family='Arial', color='black'))

# Save as HTML (Task 3 requirements ke mutabik)
fig.write_html("country_sales_treemap.html")
fig.show()

import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Data load karna
df = pd.read_csv('cleaned_ecommerce.csv')

# 2. Descriptive Statistics (Mean, Median, Mode, Std Dev, Variance)
print("="*50)
print("1. DESCRIPTIVE STATISTICS")
print("="*50)
stats_summary = df[['Quantity', 'TotalAmount']].describe()

# Variance aur Mode alag se calculate karke add karenge
stats_summary.loc['variance'] = df[['Quantity', 'TotalAmount']].var()
stats_summary.loc['mode'] = df[['Quantity', 'TotalAmount']].mode().iloc[0]

print(stats_summary.round(2))

# 3. Skewness & Kurtosis (Shape of Distribution)
print("\n" + "="*50)
print("2. DISTRIBUTION SHAPE (SKEWNESS & KURTOSIS)")
print("="*50)
for col in ['Quantity', 'TotalAmount']:
    print(f"[{col}]")
    print(f"  Skewness : {stats.skew(df[col].dropna()):.2f}")
    print(f"  Kurtosis : {stats.kurtosis(df[col].dropna()):.2f}\n")

# --- HYPOTHESIS TESTING (T-TEST) ---
print("="*50)
print("3. INFERENTIAL STATISTICS (HYPOTHESIS TESTING)")
print("="*50)

# Splitting data into United Kingdom and Non-United Kingdom groups
uk_sales = df[df['Country'] == 'United Kingdom']['TotalAmount'].dropna()
non_uk_sales = df[df['Country'] != 'United Kingdom']['TotalAmount'].dropna()

print(f"UK Transactions Count: {len(uk_sales)}")
print(f"Non-UK Transactions Count: {len(non_uk_sales)}\n")

# Performing Independent Two-Sample T-Test (Welch's T-Test due to unequal variances)
t_stat, p_val = stats.ttest_ind(uk_sales, non_uk_sales, equal_var=False)

print(f"T-Statistic value : {t_stat:.4f}")
print(f"P-Value          : {p_val}")

# Checking statistical significance at Alpha = 0.05
alpha = 0.05
if p_val < alpha:
    print("\nResult: Reject the Null Hypothesis (Statistically Significant)")
    print("Insight: There is a significant difference in the average spending behavior between UK and Non-UK customers.")
else:
    print("\nResult: Fail to Reject the Null Hypothesis (Not Statistically Significant)")
    print("Insight: The average spending behavior between UK and Non-UK customers is statistically similar.")



import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

print("="*60)
print("5. CUSTOMER SEGMENTATION USING K-MEANS CLUSTERING")
print("="*60)

# 1. RFM Feature Engineering
# Calculate Latest Date in dataset to calculate Recency
latest_date = df['InvoiceDate'].max()

rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (latest_date - x.max()).days, # Recency
    'InvoiceNo': 'nunique',                               # Frequency
    'TotalAmount': 'sum'                                  # Monetary
}).reset_index()

rfm.columns = ['CustomerID', 'Recency', 'Frequency', 'Monetary']
print("Engineered RFM Features (First 5 Rows):")
print(rfm.head())

# 2. Scaling the Features (Crucial for K-Means)
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency', 'Frequency', 'Monetary']])

# 3. Applying K-Means Clustering (Setting K=3 for Low, Medium, High Value Segments)
print("\nTraining K-Means Model...")
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

# 4. Analyzing the Profiles of Each Cluster
print("\n" + "-"*40)
print("Cluster Profile Summary (Mean Values):")
print("-"*40)
cluster_profile = rfm.groupby('Cluster').agg({
    'Recency': 'mean',
    'Frequency': 'mean',
    'Monetary': 'mean',
    'CustomerID': 'count'
}).rename(columns={'CustomerID': 'Customer_Count'}).reset_index()

print(cluster_profile.round(2))

# 5. Visualizing the Clusters (Scatter Plot: Frequency vs Monetary)
plt.figure(figsize=(10, 6))
sns.scatterplot(data=rfm, x='Frequency', y='Monetary', hue='Cluster', palette='Set1', alpha=0.7)
plt.title('Customer Segments Based on K-Means Clustering', fontsize=14, fontweight='bold')
plt.xlabel('Frequency (Number of Orders)')
plt.ylabel('Monetary (Total Spend)')
plt.yscale('log') # Using log scale due to high extreme outliers found in Task 4.1
plt.xscale('log')
plt.legend(title='Cluster')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('customer_clusters.png', dpi=300)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("="*60)
print("6. PREDICTIVE MODELING FOR CUSTOMER VALUE CLASS")
print("="*60)

# 1. Defining Target Variable
# Target = 1 if customer belongs to Cluster 1 or 2 (Active/High Value), Target = 0 if Cluster 0 (Low Value)
rfm['Is_High_Value'] = np.where(rfm['Cluster'].isin([1, 2]), 1, 0)

X = rfm[['Recency', 'Frequency']]
y = rfm['Is_High_Value']

# 2. Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training Features Shape: {X_train.shape}")
print(f"Testing Features Shape : {X_test.shape}\n")

# 3. Training Logistic Regression
print("Training Logistic Regression Model...")
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_preds = lr_model.predict(X_test)

# 4. Training Decision Tree Classifier
print("Training Decision Tree Model...")
dt_model = DecisionTreeClassifier(max_depth=3, random_state=42)
dt_model.fit(X_train, y_train)
dt_preds = dt_model.predict(X_test)

# 5. Evaluation Function
def evaluate_model(predictions, model_name):
    print(f"\n--- {model_name} Performance ---")
    print(f"Accuracy  : {accuracy_score(y_test, predictions)*100:.2f}%")
    print(f"Precision : {precision_score(y_test, predictions)*100:.2f}%")
    print(f"Recall    : {recall_score(y_test, predictions)*100:.2f}%")
    print(f"F1-Score  : {f1_score(y_test, predictions)*100:.2f}%")

# Evaluate both models
evaluate_model(lr_preds, "Logistic Regression")
evaluate_model(dt_preds, "Decision Tree")

import pandas as pd
import os
import datetime

def run_automated_pipeline(input_file_path, output_directory):
    print(f" [{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting Automated E-Commerce Pipeline...")
    if not os.path.exists(input_file_path):
        print(f" Error: Input file missing at {input_file_path}")
        return
    try:
        df = pd.read_csv(input_file_path, encoding='ISO-8859-1')
    except Exception:
        df = pd.read_csv(input_file_path, encoding='cp1252')

    print(" Raw transactional records successfully loaded with special character support.")

    initial_rows = len(df)
    df.drop_duplicates(inplace=True)
    df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

    if 'TotalAmount' not in df.columns:
        df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

    print(f"🧹 Data cleaning complete. Removed {initial_rows - len(df)} duplicate rows.")

    total_revenue = df['TotalAmount'].sum()
    total_quantity = df['Quantity'].sum()
    total_transactions = df['InvoiceNo'].nunique() if 'InvoiceNo' in df.columns else df['InvoiceDate'].nunique()
    aov = total_revenue / total_transactions if total_transactions > 0 else 0

    print("\n==========================================")
    print("      LIVE PRODUCTION KPI SUMMARY         ")
    print("==========================================")
    print(f" Total Revenue:       ${total_revenue:,.2f}")
    print(f" Total Quantity Sold: {total_quantity:,} Units")
    print(f" Total Transactions:  {total_transactions:,} Invoices")
    print(f" Average Order Value: ${aov:.2f}")
    print("==========================================\n")

    os.makedirs(output_directory, exist_ok=True)
    output_file_path = os.path.join(output_directory, 'automated_sales_summary.csv')
    df.to_csv(output_file_path, index=False)

    print(f" Cleaned dataset successfully refreshed and saved to: {output_file_path}")
    print(" End-to-End Pipeline Execution Successful!")

if __name__ == "__main__":
    INPUT_RAW_DATA = "data.csv"
    OUTPUT_PROCESSED_DIR = "processed_output/"

    run_automated_pipeline(INPUT_RAW_DATA, OUTPUT_PROCESSED_DIR)